spring.application.name=paper3
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/quantum
spring.datasource.username=quantum_admin
spring.datasource.password=quantum123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=quantum_schema
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.storage=D:\AJVRPS TECH\researchpaper\papers\processing papers\Quantum-Inspired Sorting Algorithmsog\filestorage